# Generated by Django 4.2.3 on 2023-08-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='body',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
